services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./system/storage:/var/www/html/system/storage
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zender
    ports:
      - "3306:3306"
